FUNK_TITLE = "Funksystem by JohnOX#0808 [ALPHA-BUILD]"
FUNK_SOUND = ""
FUNK_HINTERGRUNDFARBE = Color(255, 255, 255)
FUNK_ÜBERMITTLUNGSDAUER = 2
FUNK_VÜBERMITTLUNGSDAUER = 1
FUNK_ABNEHMBAR = false